[project]
name = "anwedungsbeispiel-wt-treiber-lib"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "seekae5", email = "luca.starnberg@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "wt-treiber-lib",
]

[project.scripts]
anwedungsbeispiel-wt-treiber-lib = "anwedungsbeispiel_wt_treiber_lib:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
wt-treiber-lib = { path = "C:/Users/Persystems/PycharmProjects/wt_treiber_V3eL/dist/wt_treiber_lib-1.0.0-py3-none-any.whl" }
